config/routes.rb
Netswork::Application.routes.draw do
  
  scope "/admin" do
    resources :diagrams
  end
  
  match 'diagrams/show/:id' => 'diagrams#show'
  match 'diagrams/create' => 'diagrams#create'
  match 'diagrams/update' => 'diagrams#udpate'
  match 'diagrams' => 'diagrams#index'
  match 'diagrams/shared' => 'diagrams#shared'

end

app/models/diagram.rb
class Diagram < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/diagrams_controller.rb
class DiagramsController < ApplicationController
  before_filter :setup_client_uuid
  # GET /diagrams
  # GET /diagrams.xml
  # GET /diagrams.json
  def index
    @diagrams = Diagram.where("cookie = ?", @client_uuid).where(:shared => false)
    puts @client_uuid
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @diagrams }
      format.json { render :json => @diagrams }
    end
  end
  
  def shared
    @diagrams = Diagram.where(:shared => true)
    puts @client_uuid
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @diagrams }
      format.json { render :json => @diagrams }
    end
  end

  # GET /diagrams/1
  # GET /diagrams/1.xml
  # GET /diagrams/1.json
  def show
    @diagram = Diagram.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @diagram }
      format.json { render :json => @diagram }
    end
  end

  # GET /diagrams/new
  # GET /diagrams/new.xml
  # GET /diagrams/new.json
  def new
    @diagram = Diagram.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @diagram }
      format.json  { render :json => @diagram }
    end
  end

  # GET /diagrams/1/edit
  def edit
    @diagram = Diagram.find(params[:id])
  end

  # POST /diagrams
  # POST /diagrams.xml
  # POST /diagrams.json
  def create
    @diagram = Diagram.new(params[:diagram])
    @diagram.cookie = @client_uuid;
    
    respond_to do |format|
      if @diagram.save
        format.html { redirect_to(@diagram, :notice => 'Diagram was successfully created.') }
        format.xml  { render :xml => @diagram, :status => :created, :location => @diagram }
        format.json { render :json => @diagram, :callback => params[:callback] }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @diagram.errors, :status => :unprocessable_entity }
        format.json  { render :json => @diagram.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /diagrams/1
  # PUT /diagrams/1.xml
  # PUT /diagrams/1.json
  def update
    @diagram = Diagram.find(params[:id])

    respond_to do |format|
      if @diagram.update_attributes(params[:diagram])
        format.html { redirect_to(@diagram, :notice => 'Diagram was successfully updated.') }
        format.xml  { head :ok }
        format.json  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @diagram.errors, :status => :unprocessable_entity }
        format.json  { render :json => @diagram.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /diagrams/1
  # DELETE /diagrams/1.xml
  # DELETE /diagrams/1.json
  def destroy
    @diagram = Diagram.find(params[:id])
    @diagram.destroy

    respond_to do |format|
      format.html { redirect_to(diagrams_url) }
      format.xml  { head :ok }
      format.json  { head :ok }
    end
  end
  
  def setup_client_uuid
    @client_uuid = cookies[:client_uuid]
    if !@client_uuid
      @client_uuid = cookies.permanent[:client_uuid] = rand(36**8).to_s(36);
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diagrams_helper.rb
module DiagramsHelper
end

app/views/diagrams/_form.html.erb
<%= form_for(@diagram) do |f| %>
  <% if @diagram.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@diagram.errors.count, "error") %> prohibited this diagram from being saved:</h2>

      <ul>
      <% @diagram.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :cookie %><br />
    <%= f.text_field :cookie %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/diagrams/edit.html.erb
<h1>Editing diagram</h1>

<%= render 'form' %>

<%= link_to 'Show', @diagram %> |
<%= link_to 'Back', diagrams_path %>

app/views/diagrams/index.html.erb
<h1>Listing diagrams</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Cookie</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @diagrams.each do |diagram| %>
  <tr>
    <td><%= diagram.title %></td>
    <td><%= diagram.content %></td>
    <td><%= diagram.cookie %></td>
    <td><%= link_to 'Show', diagram %></td>
    <td><%= link_to 'Edit', edit_diagram_path(diagram) %></td>
    <td><%= link_to 'Destroy', diagram, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Diagram', new_diagram_path %>

app/views/diagrams/new.html.erb
<h1>New diagram</h1>

<%= render 'form' %>

<%= link_to 'Back', diagrams_path %>

app/views/diagrams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @diagram.title %>
</p>

<p>
  <b>Content:</b>
  <%= @diagram.content %>
</p>

<p>
  <b>Cookie:</b>
  <%= @diagram.cookie %>
</p>


<%= link_to 'Edit', edit_diagram_path(@diagram) %> |
<%= link_to 'Back', diagrams_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Netswork</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>